module.exports = {
  // One-Handed Swords
  Blade: {},
  Falchion: {},
  Sword: {},
  Rapier: {},
  Scimiter: {},
  Flamberg: {},
  Haedonggum: {},
  Saber: {},
  Tsurugi: {},
  Cutlus: {},
  Excalibur: {},

  // Two-Handed Swords
  Katana: {},
  'Heavy Sword': {},
  'Bastard Sword': {},
  Slayer: {},
  'Broad Sword': {},
  Claymore: {},
  'Two-Handed Sword': {},
  Muramasa: {},
  Masamune: {},
  'Dragon Slayer': {},
  Schweizersabel: {},
  Zweihander: {},

  // Axes
  Axe: {},
  Cleaver: {},
  Hammer: {},
  Buster: {},
  'Battle Axe': {},
  'Two-Handed Axe': {},
  Guillotine: {},
  Slaughter: {},
  Tomahawk: {},
  'Doom Slayer': {},

  // Bows
  'Novice Bow': {},
  Bow: {},
  'Composite Bow': {},
  'Cross Bow': {},
  'Great Bow': {},
  Arbalest: {},
  'Crimson Bow': {},
  'Elven Bow': {},
  'Gakkung Bow': {},
  'Hunter Bow': {},
  Ballista: {},
  'Ixion Wings': {},

  // Rods
  'Novice Rod': {},
  Rod: {},
  Staff: {},
  Wand: {},
  'Arc Wand': {},
  'Evil Bone Wand': {},
  'Healing Staff': {},
  'Mighty Staff': {},
  'Wand of Occult': {},
  "Warlock's Magic Wand": {},
  'Thorn Staff of Darkness': {},
  'Holy Staff': {},
  Eraser: {},

  // Knuckles
  Finger: {},
  Fist: {},
  Claw: {},
  'Knuckle Dusters': {},
  'Studded Knuckles': {},
  'Glorious Claw': {},
  "Sura's Rampage": {},
  Spartacus: {},
  'Hatii Claw': {}
};
